server:
  port: 8090

spring:
  application:
    name: analyzer-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/analyzer
    username: analyzer
    password: analyzer
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analyzer-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
  grpc:
    server:
      port: 0
      security:
        enabled: false

app:
  kafka:
    topics:
      user-actions: stats.user-actions.v1
      events-similarity: stats.events-similarity.v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    metadata-map: # ← добавьте
      gRPC.port: ${grpc.server.port:0}        # ← пробрасываем порт
      grpcPort: ${grpc.server.port:0}         # ← дублируем для совместимости

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.kafka: INFO