CREATE TABLE IF NOT EXISTS user_actions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      INTEGER NOT NULL,
    event_id     INTEGER NOT NULL,
    action_type  VARCHAR(20) NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event_similarity (
    event_a_id INTEGER NOT NULL,
    event_b_id INTEGER NOT NULL,
    score      DOUBLE PRECISION NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_event_a_b PRIMARY KEY (event_a_id,  event_b_id)
);