services:
  # ========== БАЗЫ ДАННЫХ ==========

  stats-db:
    image: postgres:18.4
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d stats -U user"]
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - stats-db-data:/var/lib/postgresql/data

  ewm-db:
    image: postgres:18.4
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d main -U user"]
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - ewm-db-data:/var/lib/postgresql/data

volumes:
  stats-db-data:
  ewm-db-data: