spring.application.name=comment-service
server.port=0

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server
spring.config.import=optional:configserver:
eureka.instance.prefer-ip-address=true

spring.main.allow-bean-definition-overriding=true

# Actuator настройки
management.endpoints.web.exposure.include=health,info,mappings,metrics,loggers
management.endpoints.enabled-by-default=true
management.endpoint.health.show-details=always
management.endpoint.mappings.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.info.enabled=true