server:
  port: 8088

spring:
  application:
    name: collector-service
  config:
    import: "optional:configserver:"
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 3

grpc:
  server:
    port: 0

app:
  kafka:
    topics:
      user-actions: stats.user-actions.v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.kafka: INFO