spring:
  application:
    name: user-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      retry:
        max-attempts: 6
        initial-interval: 2000
        max-interval: 5000
  config:
    import: "optional:configserver:"

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

logging:
  level:
    ru.practicum: DEBUG