spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    gateway:
      actuator:
       enabled: true
      server:
        webflux:
          routes:
            - id: request-service
              uri: lb://REQUEST-SERVICE
              predicates:
                - Path=/users/*/requests/**,/users/*/events/*/requests/**
            - id: comment-service
              uri: lb://COMMENT-SERVICE
              predicates:
                - Path=/comments/**,/admin/comments/**,/users/*/comments/**,/users/*/events/*/comments/**
            - id: category-service
              uri: lb://CATEGORY-SERVICE
              predicates:
                - Path=/categories/**,/admin/categories/**
            - id: event-service
              uri: lb://EVENT-SERVICE
              predicates:
                - Path=/events/**,/admin/events/**,/compilations/**,/admin/compilations/**,/users/*/events/**
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**,/admin/users/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG