spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    gateway:
      actuator:
        enabled: true
      # ⬇️ ГЛАВНОЕ: УБРАЛ "server: webflux:"
      routes:
        - id: request-service
          uri: lb://REQUEST-SERVICE
          predicates:
            - Path=/users/*/events/*/requests/**,/users/*/requests/**
          filters:
            - StripPrefix=0

        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/users/*/events/*/comments/**,/users/*/comments/**,/admin/comments/**,/comments/**
          filters:
            - StripPrefix=0

        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/categories/**,/admin/categories/**
          filters:
            - StripPrefix=0

        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/users/*/events/**,/events/**,/admin/events/**,/compilations/**,/admin/compilations/**
          filters:
            - StripPrefix=0

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**,/admin/users/**
          filters:
            - StripPrefix=0