server:
  port: 8088

spring:
  application:
    name: collector-service
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      acks: all
      retries: 3

grpc:
  server:
    port: 0
    security:
      enabled: false

app:
  kafka:
    topics:
      user-actions: stats.user-actions.v1

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.kafka: INFO