spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stats
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

format:
  pattern:
    datetime: yyyy-MM-dd HH:mm:ss

stats-client:
  retry:
    backoff-period: 3000
    max-attempts: 3