spring.cloud.gateway.server.webflux.routes[0].id=event-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://EVENT-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/events/**,/admin/events/**,/compilations/**,/admin/compilations/**,/users/*/events/**

spring.cloud.gateway.server.webflux.routes[1].id=request-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://REQUEST-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/*/requests/**,/users/*/events/*/requests/**