# Gateway routes
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**,/admin/users/**

spring.cloud.gateway.server.webflux.routes[1].id=category-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://CATEGORY-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/categories/**,/admin/categories/**

spring.cloud.gateway.server.webflux.routes[2].id=event-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://EVENT-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/events/**,/admin/events/**,/compilations/**,/admin/compilations/**,/users/*/events/**

spring.cloud.gateway.server.webflux.routes[3].id=request-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://REQUEST-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/users/*/requests/**,/users/*/events/*/requests/**

spring.cloud.gateway.server.webflux.routes[4].id=comment-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://COMMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/comments/**,/admin/comments/**,/users/*/comments/**,/users/*/events/*/comments/**

# Включение Gateway Actuator
spring.cloud.gateway.actuator.enabled=true

# Management
management.endpoints.web.exposure.include=*

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=DEBUG
logging.level.reactor.netty=DEBUG