spring.application.name=main-service
server.port=0
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
stats.server.url=http://stats-server:9090

# Connection to Postgres DB
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/main
spring.datasource.username=user
spring.datasource.password=password

#spring.profiles.active=h2

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

format.pattern.datetime=yyyy-MM-dd HH:mm:ss