# Server port
server.port=8080

# Stats Server URL (localhost ??? ????????? ??????????)
stats.server.url=http://localhost:9090

# Connection to H2 DB (in-memory)
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:ewm_main
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

# H2 Console (??? ????????? ?? ????? ???-?????????)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Date format
format.pattern.datetime=yyyy-MM-dd HH:mm:ss